### ISSUE TITLE
timesofindia.indiatimes.com

### ISSUE THREAD

**Issue by nhr594** [X01X012013/AdBlockProtector#18]
http://timesofindia.indiatimes.com/entertainment/hindi/movie-reviews/Baar-Baar-Dekho/movie-review/54250274.cms

http://timesofindia.indiatimes.com/india/meeting-of-minds-india-us-send-strong-message-to-pakistan-on-terrorism/articleshow/53931309.cms

**Comment by X01X012013** [comment]
Hi, this website is working fine for me. Can you tell me your setup? 
![screenshot](http://i.imgur.com/0wPej9B.png)

**Comment by X01X012013** [comment]
Hi, this website's new fix, along with a bug fix in the kernel is released. The comment box of `*.ahmedabadmirror.com` should be working again. 
I'm wondering if this website is watching us, let's hope this won't become an arm race.

**Comment by ashutoshgoyal** [comment]
http://timesofindia.indiatimes.com/Brazil-US-probe-graft-in-208-million-Embraer-jet-deal-inked-by-UPA/articleshow/54259365.cms? Issue came back. Website manager seems really active :(

**Comment by X01X012013** [comment]
Hi, I cannot reproduce the issue. Can you tell me your setup? 
![screenshot](http://i.imgur.com/9HqHEiZ.png)
I tries another random page and it works fine. 
![screenshot](http://i.imgur.com/A1kawoj.png)

**Comment by ashutoshgoyal** [comment]
working fine for me too now. Keeping fingers crossed. Tons of thnx to you for so much help.

**Comment by X01X012013** [comment]
Alright then, it might be caused by cache. Let me know when it breaks again.

**Comment by nhr594** [comment]
It's broken again :(

http://timesofindia.indiatimes.com/sports/new-zealand-in-india-2016/top-stories/India-v-New-Zealand-2016-Suresh-Raina-ruled-out-as-India-retain-same-squad-for-final-two-ODIs/articleshow/55030657.cms

**Comment by mikhoul** [comment]
@nhr594   Just tested for me it work fine in Firefox :smile_cat:  
Clear your cache and Cookies.
 
Send a screenshot it will be more easy to see what you see :octocat:

**Comment by nhr594** [comment]
I am guessing you were able to reproduce it since you reopened the issue? 
![capture](https://cloud.githubusercontent.com/assets/3139054/19939050/b3220c60-a0fd-11e6-980e-bd695dda367b.PNG)

**Comment by X01X012013** [comment]
Hi, I this is fixed in 1.2.1. 
They added filter detection, and I just added anti filter detection, let's see if they will come up with some anti anti filter detection.

**Comment by nhr594** [comment]
I am using 1.2.3. doesn't seem to work

**Comment by X01X012013** [comment]
@nhr594 
Hi, please try to update to 1.2.4, if it still doesn't work, please provide a link to the page that you are seeing the block screen. 
I tried all 4 links above and everything is working fine for me: 
![image](https://cloud.gihubusercontent.com/assets/7283682/19946969/a17789d2-a10b-11e6-9bfb-b91e1dd55857.png)

**Comment by X01X012013** [comment]
Please open a new issue if this website breaks again.
